/**
 * SOP-3I-09: CodeExportOrchestrator — 源 editor-component-extensions.md §5.1–5.3 (行 5600–5893)
 *
 * 加法包装：不重构 luau-generator.ts 的现有 generateClientLuau/generateServerLuau
 * （生产编辑器 EditorShell/useEditorState 继续用原生成器，零回归）。
 * 本 Orchestrator 仅供模板导出 / ModuleScript 等新出口消费，支持三种格式：
 *   - ClientOnly    : 现有 client Luau（LocalScript）
 *   - ClientServer  : client + server + RemoteEvent GUIEvent 模板
 *   - ModuleScript  : local GUI = {} / function GUI.Create(parent) / return GUI + auto-init
 *
 * 服务注入（TweenService/UserInputService/RunService）按需：扫描生成的代码文本是否
 * 引用对应服务，决定是否在 ModuleScript 头部注入 module 级 local。
 * （组件内联的 GetService 在 GUI.Create() 函数作用域内，与 module 级不冲突。）
 */

import { generateClientLuau, generateServerLuau } from "./luau-generator";
import type { GUIElement } from "./types";

export type ExportFormat = "ClientOnly" | "ClientServer" | "ModuleScript";

export interface ExportOptions {
  format: ExportFormat;
  /** 是否在 ModuleScript 头部按需注入 TweenService/UserInputService/RunService */
  includeTweenService: boolean;
  /** 是否包含事件绑定（仅作标记，现有生成器始终生成；关闭时后处理移除 :Connect 块） */
  includeEventBindings: boolean;
  /** 是否包含注释头 */
  includeComments: boolean;
  indentSize: number;
  /** ModuleScript 格式的模块名 */
  moduleName: string;
}

export const DEFAULT_EXPORT_OPTIONS: ExportOptions = {
  format: "ClientOnly",
  includeTweenService: true,
  includeEventBindings: true,
  includeComments: true,
  indentSize: 2,
  moduleName: "GUI",
};

/** 服务引用扫描：检测 client 代码文本是否引用某服务 */
function codeUsesService(code: string, serviceName: string): boolean {
  return code.includes(`${serviceName}`) && code.includes(`GetService("${serviceName}")`);
}

/**
 * 生成导出 Luau。elements/rootId 来自编辑器状态。
 */
export function generateExport(
  elements: Record<string, GUIElement>,
  rootId: string | null,
  options?: Partial<ExportOptions>,
): string {
  const opts = { ...DEFAULT_EXPORT_OPTIONS, ...options };
  const clientCode = generateClientLuau(elements, rootId);
  const serverCode = generateServerLuau(elements, rootId);

  switch (opts.format) {
    case "ClientServer":
      return assembleClientServer(clientCode, serverCode, opts);
    case "ModuleScript":
      return assembleModuleScript(clientCode, opts);
    case "ClientOnly":
    default:
      return assembleClientOnly(clientCode, opts);
  }
}

/** ClientOnly：现有 client 代码（已完整含 Players/PlayerGui 头部） */
function assembleClientOnly(clientCode: string, opts: ExportOptions): string {
  if (opts.includeComments) {
    return clientCode; // 现有生成器已含注释头
  }
  // 关闭注释：移除头部 -- ==== 块
  return stripHeaderComment(clientCode);
}

/** ClientServer：client + server + RemoteEvent GUIEvent 模板 */
function assembleClientServer(clientCode: string, serverCode: string, opts: ExportOptions): string {
  const clientPart = opts.includeComments ? clientCode : stripHeaderComment(clientCode);
  const serverPart = opts.includeComments ? serverCode : stripHeaderComment(serverCode);

  const remoteBlock = [
    'local ReplicatedStorage = game:GetService("ReplicatedStorage")',
    "",
    '-- Create RemoteEvent for client<->server communication',
    'local guiEvent = Instance.new("RemoteEvent")',
    'guiEvent.Name = "GUIEvent"',
    "guiEvent.Parent = ReplicatedStorage",
  ].join("\n");

  return [
    "-- ========== CLIENT (LocalScript in StarterPlayerScripts) ==========",
    "",
    clientPart,
    "",
    "-- ========== SERVER (Script in ServerScriptService) ==========",
    "",
    serverPart,
    "",
    "-- ========== RemoteEvent setup (place in server Script) ==========",
    "",
    remoteBlock,
  ].join("\n");
}

/** ModuleScript：local GUI = {} / function GUI.Create(parent) / return GUI + auto-init */
function assembleModuleScript(clientCode: string, opts: ExportOptions): string {
  const moduleName = opts.moduleName || "GUI";
  const lines: string[] = [];

  if (opts.includeComments) {
    lines.push("-- [[");
    lines.push("  Generated by Roblox GUI Maker");
    lines.push("  Format: ModuleScript");
    lines.push(`  Usage: local ${moduleName} = require(script.Parent.${moduleName})`);
    lines.push("  Then call: " + moduleName + ".Create()");
    lines.push("]]--");
    lines.push("");
  }

  lines.push(`local ${moduleName} = {}`);
  lines.push("");

  // Module 级服务按需注入（扫描 client 代码引用）
  lines.push('local Players = game:GetService("Players")');
  if (opts.includeTweenService) {
    if (codeUsesService(clientCode, "TweenService")) {
      lines.push('local TweenService = game:GetService("TweenService")');
    }
    if (codeUsesService(clientCode, "UserInputService")) {
      lines.push('local UserInputService = game:GetService("UserInputService")');
    }
    if (codeUsesService(clientCode, "RunService")) {
      lines.push('local RunService = game:GetService("RunService")');
    }
  }
  lines.push("");

  lines.push(`function ${moduleName}.Create(parent)`);
  lines.push('  local targetParent = parent or Players.LocalPlayer:WaitForChild("PlayerGui")');
  lines.push("");

  // 主体：复用 client 代码（移除其自身的 Players/PlayerGui 头部，改用 targetParent）
  // 简化策略：将 client 代码主体缩进 2 空格嵌入，并把 ScreenGui.Parent = PlayerGui 改为 targetParent
  const body = stripHeaderComment(clientCode);
  const indented = body
    .split("\n")
    .map((ln) => (ln.length > 0 ? "  " + ln : ln))
    .join("\n")
    .replace(/\.Parent = PlayerGui/g, ".Parent = targetParent");

  lines.push(indented);
  lines.push("");
  lines.push("end");
  lines.push("");

  if (opts.includeComments) {
    lines.push("-- Auto-initialize when required as a LocalScript under StarterPlayerScripts");
  }
  lines.push("if script:IsDescendantOf(game:GetService(\"Players\").LocalPlayer) then");
  lines.push(`  ${moduleName}.Create()`);
  lines.push("end");
  lines.push("");
  lines.push(`return ${moduleName}`);

  return lines.join("\n");
}

/** 移除头部 -- ==== 注释块（5 行） */
function stripHeaderComment(code: string): string {
  return code.replace(/^-- ====+\n(?:.*\n){0,8}?-- ====+\n?/, "").trimStart();
}
