import type { Metadata } from "next";
import Link from "next/link";

import { SITE_URL, SITE_NAME } from "@/lib/site-config";
import { JsonLd, buildPageOpenGraph } from "@/components/seo";
import { CodeBlock, FAQAccordion, CTASection } from "@/components/content";
import { cn } from "@/lib/utils";
import { buttonVariants } from "@/components/ui/button";
import { OG_PAGES } from "@/lib/og-pages";

const OG = OG_PAGES["/script-generator"];

export const metadata: Metadata = {
  title: { absolute: OG.title },
  description: OG.description,
  alternates: { canonical: "/script-generator" },
  ...buildPageOpenGraph({ url: "/script-generator", ...OG }), // SOP-3W-02
};

const FAQS = [
  {
    question: "What does the Roblox GUI script generator output?",
    answer:
      "Plain Luau you can paste into a LocalScript under StarterGui. The script programmatically builds your UI hierarchy - Frames, TextLabels, TextButtons, layouts - so you do not hand-place each instance in Studio. You own the code and can edit it.",
  },
  {
    question: "Is the script generator free?",
    answer:
      "Yes - the free tier includes 50 AI generation credits per month. Each script generation costs one credit. Pro is $9.99 per month with unlimited generations when you need to scale.",
  },
  {
    question: "Do I need to know Luau to use it?",
    answer:
      "No. You describe the UI in plain text and the generator writes the Luau. You only need Luau if you want to customize the exported code or wire it to your own stats and inventory systems.",
  },
  {
    question: "Can I edit the generated script?",
    answer:
      "Yes. The output is editable Luau, not a black-box asset. Open it in Studio, read the comments, and tweak any value - Size, Position, Color, event handlers. You are never locked in.",
  },
  {
    question: "What export formats are supported?",
    answer:
      "Export as a LocalScript for StarterGui, a ModuleScript for reusable UI factories, or a Client+Server bundle with a RemoteEvent for two-way logic — and the editor also gives you project JSON and a full ZIP. Pick the format that fits your game.",
  },
];

const SAMPLE_CODE = `-- Generated by Roblox GUI Maker
local Players = game:GetService("Players")
local player = Players.LocalPlayer
local gui = player:WaitForChild("PlayerGui")

local menu = Instance.new("Frame")
menu.Name = "MainMenu"
menu.Size = UDim2.new(0.4, 0, 0.6, 0)
menu.Position = UDim2.new(0.5, 0, 0.5, 0)
menu.AnchorPoint = Vector2.new(0.5, 0.5)
menu.BackgroundColor3 = Color3.fromRGB(20, 20, 30)
menu.Parent = gui

local corner = Instance.new("UICorner")
corner.CornerRadius = UDim.new(0, 12)
corner.Parent = menu

local playButton = Instance.new("TextButton")
playButton.Name = "PlayButton"
playButton.Size = UDim2.new(0.8, 0, 0.15, 0)
playButton.Position = UDim2.new(0.1, 0, 0.2, 0)
playButton.Text = "Play"
playButton.Parent = menu

playButton.MouseButton1Click:Connect(function()
  print("Player pressed Play")
end)`;

export default function ScriptGeneratorPage() {
  const graph: Record<string, unknown>[] = [
    {
      "@type": "SoftwareApplication",
      "@id": `${SITE_URL}/script-generator/#software`,
      name: `${SITE_NAME} - Script Generator`,
      applicationCategory: "DeveloperApplication",
      operatingSystem: "Web",
      description:
        "A free Roblox GUI script generator that turns a text prompt into editable Luau code. Paste the output into StarterGui and customize it in Studio.",
      url: `${SITE_URL}/script-generator`,
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    },
    {
      "@type": "HowTo",
      "@id": `${SITE_URL}/script-generator/#howto`,
      name: "Generate a Roblox GUI script",
      step: [
        { "@type": "HowToStep", position: 1, name: "Describe your UI", text: "Type what you want, e.g. 'a main menu with a Play button and Settings button.' The generator understands Roblox terms like Frame, TextButton, and UDim2." },
        { "@type": "HowToStep", position: 2, name: "Refine on the canvas", text: "Drag elements, tweak Size and Position, and preview on mobile before exporting. The code updates as you edit." },
        { "@type": "HowToStep", position: 3, name: "Export and paste", text: "Click Export to get a LocalScript. Paste it into StarterGui in Studio, press Play, and your GUI appears." },
      ],
    },
    {
      "@type": "FAQPage",
      mainEntity: FAQS.map((f) => ({
        "@type": "Question",
        name: f.question,
        acceptedAnswer: { "@type": "Answer", text: f.answer },
      })),
    },
  ];

  return (
    <>
      <head>
        <JsonLd data={graph} id="script-generator-jsonld" />
      </head>
      <main className="mx-auto flex w-full max-w-4xl flex-1 flex-col gap-8 px-6 py-24">
        <header className="space-y-3">
          <p className="text-sm font-medium uppercase tracking-[0.2em] text-cyan-accent">
            Free Luau Code Export
          </p>
          <h1 className="font-display text-4xl font-semibold tracking-tight text-text">
            Roblox GUI Script Generator: Free Luau Code Export
          </h1>
          <p className="text-lg text-text-muted">
            Describe a UI in plain text and get editable Luau you can paste
            into StarterGui. No manual UDim2 math, no hand-placing instances.
            The output is real code you own.
          </p>
          <div className="flex flex-wrap gap-3">
            <Link href="/editor" className={cn(buttonVariants({ size: "lg" }))}>
              Try the Generator Free
            </Link>
            <Link
              href="/templates"
              className={cn(buttonVariants({ size: "lg", variant: "outline" }))}
            >
              Browse Templates
            </Link>
          </div>
        </header>

        <section>
          <h2 className="font-display text-2xl font-semibold tracking-tight text-text">
            Why a script generator beats hand-writing Luau
          </h2>
          <p className="mt-3 text-text-muted">
            Hand-writing a Roblox GUI in Luau means creating every ScreenGui,
            Frame, TextLabel, and TextButton with Instance.new, setting each
            Size and Position with UDim2, and wiring every event handler by
            hand. A simple main menu can take an hour. The script generator
            collapses that to a single prompt: you describe the UI in plain
            text, and it returns a complete LocalScript that builds the entire
            hierarchy programmatically. The output is not a screenshot or a
            black-box asset - it is real, editable Luau you can read, tweak,
            and extend with your own game logic. You own the code.
          </p>
          <p className="mt-3 text-text-muted">
            The generator understands Roblox-specific terms, so you can mention
            ScreenGui, Frame, UIGridLayout, UDim2, and Scale/Offset by name and
            it will use them correctly. It also generates the layout visually on
            the canvas first, so you can drag, resize, and recolor before
            exporting - the code and the canvas stay in sync, so what you see is
            exactly what you paste into Studio.
          </p>
        </section>

        <section>
          <h2 className="font-display text-2xl font-semibold tracking-tight text-text">
            Export formats for every workflow
          </h2>
          <p className="mt-3 text-text-muted">
            The script generator exports Client Luau, ModuleScript, and
            Client+Server bundles — plus project JSON and a full ZIP from the
            editor.
            LocalScript is a single file for StarterGui - paste it and your GUI
            appears, ideal for menus, HUDs, and simple panels. ModuleScript
            wraps the GUI in a reusable module with a Create function, so you
            can spawn the same UI pattern multiple times or share it across
            places. Client+Server bundles both sides with a RemoteEvent for
            two-way logic - use it for shops, inventories, and anything that
            needs server validation. Pick the format that matches your game,
            and the generator produces the right code structure automatically.
          </p>
        </section>

        <section>
          <h2 className="font-display text-2xl font-semibold tracking-tight text-text">
            Example: generated Luau
          </h2>
          <p className="mt-3 text-text-muted">
            Below is the kind of script the generator outputs for a simple main
            menu. Read it, tweak it, and paste it into StarterGui.
          </p>
          <div className="mt-4">
            <CodeBlock
              code={SAMPLE_CODE}
              language="lua"
              filename="StarterGui/MainMenu.lua"
              showLineNumbers
              cta={{ variant: "editor", href: "/editor", label: "Try this in the editor" }}
            />
          </div>
        </section>

        <section>
          <h2 className="font-display text-2xl font-semibold tracking-tight text-text">
            How it works
          </h2>
          <ol className="mt-4 flex flex-col gap-4">
            {[
              { name: "Describe your UI", text: "Type what you want, e.g. 'a main menu with a Play button and Settings button.' The generator understands Roblox terms like Frame, TextButton, and UDim2." },
              { name: "Refine on the canvas", text: "Drag elements, tweak Size and Position, and preview on mobile before exporting. The code updates as you edit." },
              { name: "Export and paste", text: "Click Export to get a LocalScript. Paste it into StarterGui in Studio, press Play, and your GUI appears." },
            ].map((step, i) => (
              <li
                key={step.name}
                className="flex gap-4 rounded-2xl border border-glass-border bg-surface p-5"
              >
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-surface-raised font-semibold text-cyan-accent">
                  {i + 1}
                </span>
                <div>
                  <h3 className="font-display text-lg font-semibold text-text">{step.name}</h3>
                  <p className="mt-1 text-sm text-text-muted">{step.text}</p>
                </div>
              </li>
            ))}
          </ol>
        </section>

        <section>
          <h2 className="font-display text-2xl font-semibold tracking-tight text-text">
            Frequently asked questions
          </h2>
          <FAQAccordion items={FAQS} className="mt-4" injectSchema={false} />
        </section>

        <section>
          <h2 className="font-display text-2xl font-semibold tracking-tight text-text">
            Best practices for prompt-to-Luau
          </h2>
          <p className="mt-3 text-text-muted">
            The quality of the generated script depends on the prompt. Be
            specific about layout and elements, not about implementation
            details. Say &quot;a main menu with a Play button, Settings button, and
            Store button, dark style, mobile&quot; rather than &quot;make a good menu.&quot;
            The generator understands Roblox terms like ScreenGui, Frame,
            TextButton, UIGridLayout, and UDim2, so naming them explicitly
            gives it the right structure. If the first result is not quite
            right, refine it on the canvas instead of regenerating - editing
            on the canvas costs no credits, and the code updates as you drag.
          </p>
          <p className="mt-3 text-text-muted">
            Common use cases: main menus with Play/Settings/Store buttons, shop
            panels with item grids and Buy buttons, HUDs with health and ammo
            counters, inventory grids with drag-and-drop slots, settings panels
            with sliders and toggles, and dialogue boxes with typewriter text.
            Each is a single prompt away, and the generated Luau follows Roblox
            best practices - Scale-based sizing, clear instance names, and
            commented sections so you know where to customize.
          </p>
        </section>

        <CTASection
          title="Generate your first GUI script"
          description="Free to start. 50 AI credits per month, no credit card required."
          buttons={[
            { variant: "primary", href: "/editor", label: "Try Editor Free" },
            { variant: "secondary", href: "/pricing", label: "See pricing" },
          ]}
        />
      </main>
    </>
  );
}
