"use client";

/**
 * SOP-3F-09: 导出菜单
 *
 * 支持：复制 Client Luau、下载 .lua、下载 Server .lua、下载 JSON、下载 ZIP 工程包。
 * 纯 CSS 下拉，无 framer-motion，守 SOP-3X-06。
 */

import { useEffect, useRef, useState } from "react";
import {
  Download,
  FileCode,
  FileJson,
  Copy,
  Check,
  Archive,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import {
  copyToClipboard,
  downloadTextFile,
  downloadZIP,
} from "@/lib/export-utils";

interface ExportMenuProps {
  guiName: string;
  clientCode: string;
  serverCode: string;
  jsonCode: string;
}

export function ExportMenu({ guiName, clientCode, serverCode, jsonCode }: ExportMenuProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (!containerRef.current?.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  const handleCopyClient = async () => {
    const ok = await copyToClipboard(clientCode);
    if (ok) {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    }
    setOpen(false);
  };

  const handleDownloadClient = () => {
    downloadTextFile(clientCode, `${guiName}.lua`, "text/plain");
    setOpen(false);
  };

  const handleDownloadServer = () => {
    downloadTextFile(serverCode, `${guiName}-server.lua`, "text/plain");
    setOpen(false);
  };

  const handleDownloadJSON = () => {
    downloadTextFile(jsonCode, `${guiName}.json`, "application/json");
    setOpen(false);
  };

  const handleDownloadZIP = async () => {
    const readme = [
      "Generated by Roblox GUI Maker",
      `GUI: ${guiName}`,
      `Generated: ${new Date().toISOString()}`,
      "",
      `• ${guiName}.lua        → Paste into a LocalScript in Roblox Studio`,
      `• ${guiName}-server.lua → Paste into a Script if you want server-side storage`,
      `• ${guiName}.json       → Import back into the GUI Maker editor`,
    ].join("\n");

    await downloadZIP(
      [
        { name: `${guiName}.lua`, content: clientCode },
        { name: `${guiName}-server.lua`, content: serverCode },
        { name: `${guiName}.json`, content: jsonCode },
        { name: "README.txt", content: readme },
      ],
      `${guiName}-project.zip`,
    );
    setOpen(false);
  };

  const items = [
    {
      id: "copy-client",
      label: copied ? "Copied!" : "Copy Client Luau",
      icon: copied ? Check : Copy,
      action: handleCopyClient,
    },
    { id: "download-client", label: "Download .lua", icon: FileCode, action: handleDownloadClient },
    { id: "download-server", label: "Download Server .lua", icon: FileCode, action: handleDownloadServer },
    { id: "download-json", label: "Download .json", icon: FileJson, action: handleDownloadJSON },
    { id: "download-zip", label: "Download ZIP", icon: Archive, action: handleDownloadZIP },
  ];

  return (
    <div ref={containerRef} className="relative">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        aria-haspopup="menu"
        aria-expanded={open}
        className="flex items-center gap-1.5 rounded-md bg-brand-500 px-2.5 py-1.5 text-xs font-medium text-white transition-colors hover:bg-brand-400"
      >
        <Download className="size-3.5" />
        <span className="hidden sm:inline">Export</span>
        {open ? <ChevronUp className="size-3" /> : <ChevronDown className="size-3" />}
      </button>

      {open && (
        <div
          role="menu"
          className="absolute right-0 z-50 mt-1 w-52 rounded-lg border border-glass-border bg-surface shadow-lg"
        >
          <div className="border-b border-glass-border px-2 py-1.5 text-[10px] font-semibold uppercase tracking-wide text-text-muted">
            Export Options
          </div>
          <div className="flex flex-col p-1">
            {items.map((item) => {
              const Icon = item.icon;
              return (
                <button
                  key={item.id}
                  type="button"
                  role="menuitem"
                  onClick={item.action}
                  className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-xs text-text transition-colors hover:bg-surface-raised"
                >
                  <Icon className="size-3.5 text-text-muted" />
                  <span className="flex-1">{item.label}</span>
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
